# Welcome to Jekyll!

# Basic Site Settings
locale                   : "en-US"
title                    : "Saber Khani"
title_separator          : "-"
name                     : &name "Saber Khani"
description              : &description "personal description"
URL                      : "https://saberkhani6688.github.io"
baseurl                  : ""
repository               : "saberkhani/saberkhani.github.io"

# Site Author
author:
  avatar           : "saber_headshot.jpg"
  name             : "Saber Khani"
  bio              : "Ph.D. Candidate in Sociology at Boston College"
  location         : "Boston, MA USA"
  employer         : "Boston College"
  email            : "khanis@bc.edu"
  googlescholar    : "https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=KOvMEfIAAAAJ"
  orcid            : "https://orcid.org/0000-0002-7896-469X"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=saber+khani"
  github           : "https://github.com/Saberkhani6688"
  linkedin         : "https://www.linkedin.com/in/saber-khani-99825722a/"

# Publication Categories
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :

staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"

atom_feed:
  hide                   : false
  path                   :

# SEO & Social Sharing
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:
  username               : &twitter

facebook:
  username               :
  app_id                 :
  publisher              :

og_image                 :

social:
  type                   :
  name                   :
  links: []

# Analytics
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      output: true
      permalink: /:path/

  - scope:
      path: ""
      type: teaching
    values:
      output: true
      permalink: /:collection/:path/

  - scope:
      path: ""
      type: publications
    values:
      output: true
      permalink: /:collection/:path/

  - scope:
      path: ""
      type: portfolio
    values:
      output: true
      permalink: /:collection/:path/

  - scope:
      path: ""
      type: talks
    values:
      output: true
      permalink: /:collection/:path/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output Settings
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Whitelist for GitHub Pages
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
