# Welcome to Jekyll!

# Basic Site Settings
locale: "en-US"
title: "Saber Khani"
title_separator: "-"
name: &name "Saber Khani"
description: &description "personal description"
url: "https://saberkhani6688.github.io"  # Include https://
baseurl: ""  # Leave empty unless using a subdirectory
repository: "saberkhani/saberkhani.github.io"

# Theme
theme: "minimal-mistakes-jekyll"

# Author Info (for sidebar/profile)
author:
  avatar: "saber_headshot.jpg"
  name: "Saber Khani"
  bio: "Ph.D. Candidate in Sociology at Boston College"
  location: "Boston, MA USA"
  employer: "Boston College"
  email: "khanis@bc.edu"
  googlescholar: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=KOvMEfIAAAAJ"
  orcid: "https://orcid.org/0000-0002-7896-469X"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=saber+khani"
  github: "https://github.com/Saberkhani6688"
  linkedin: "https://www.linkedin.com/in/saber-khani-99825722a/"

# Publication Categories
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Site Settings
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Comments (disabled by default)
comments:
  provider: false

# Atom/RSS Feed
atom_feed:
  hide: false

# Analytics (disabled by default)
analytics:
  provider: false

# Social Sharing
twitter:
  username: &twitter
social:
  type: "Person"
  name: "Saber Khani"
  links: []  # Add if needed

# Markdown Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Kramdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Includes and Excludes
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Output
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
