title: "Saber Khani"
email: khanis@bc.edu
description: >-
  Ph.D. Candidate in Sociology at Boston College
baseurl: ""
url: "https://saberkhani6688.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-remote-theme

author:
  name: "Saber Khani"
  avatar: "saber_headshot.jpg"
  bio: "Ph.D. Candidate in Sociology at Boston College"
  location: "Boston, MA USA"
  email: "khanis@bc.edu"
  github: "https://github.com/Saberkhani6688"
  linkedin: "https://www.linkedin.com/in/saber-khani-99825722a/"
  googlescholar: "https://scholar.google.com/citations?user=KOvMEfIAAAAJ"
  orcid: "https://orcid.org/0000-0002-7896-469X"
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=saber+khani"

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true

markdown: kramdown
highlighter: rouge
theme: null
